from datetime import datetime
datenow1=datetime.now().date()
print("Fecha1:",datenow1)
print("Año fecha1:",datenow1.year)
print("Mes fecha1:",datenow1.month)
print("Día fecha1:",datenow1.day)
#print("Hora fecha1:",datenow1.hour)  No esta disponible por que la variable solo contiene la fecha
datenow2=datetime.now()
print("Fecha2:",datenow2)
print("Año fecha2",datenow2.year)
print("mes Fecha2",datenow2.month)
print("dia Fecha2",datenow2.day)
print("hora Fecha2",datenow2.hour)
print("minuto Fecha2",datenow2.minute)
print("Segundos Fecha",datenow2.second)
print("microsegundos Fecha2",datenow2.microsecond)
datenow3=datetime.now()
print("Fecha3:",datenow3)
print("Año fecha3",datenow3.year)
print("mes Fecha3",datenow3.month)
print("dia Fecha3",datenow3.day)
print("hora Fecha3",datenow3.hour)
print("minuto Fecha3",datenow3.minute)
print("Segundos Fecha3",datenow3.second)
print("microsegundos Fecha3",datenow3.microsecond)

